Move to Font Awesome 6 icons
symfony2admingenerator/FormExtensionsBundle pull request #85
Opened 2023-11-14 21:03 UTC by tobias-93

2023-11-16 19:18 UTC, bobvandevijver requested changes

2023-11-16 19:18 UTC, bobvandevijver commented on Resources/public/bootstrap-collection/css/bootstrap-collection.min.css
I believe this change can be undone

2023-11-16 19:18 UTC, bobvandevijver commented on Resources/public/bootstrap-collection/css/bootstrap-collection.css
I believe this change can be undone

2023-11-16 19:18 UTC, bobvandevijver commented on Resources/views/Form/form_html.html.twig
> +    {% set widgetIcon = 'fa-regular fa-calendar-days' %}
`fa` indicator class is now missing?

2023-11-16 19:18 UTC, bobvandevijver commented on Resources/views/Form/form_html.html.twig
> +    {% set widgetIcon = 'fa-regular fa-calendar-days' %}
fa indicator class is now missing?

2023-11-16 19:18 UTC, bobvandevijver commented on Resources/views/Form/form_html.html.twig
> +    {% set widgetIcon = 'fa-regular fa-clock' %}
fa indicator class is now missing?

2023-11-21 19:59 UTC, tobias-93 commented on Resources/views/Form/form_html.html.twig
> +    {% set widgetIcon = 'fa-regular fa-calendar-days' %}
It is not necessary anymore

2023-11-21 20:00 UTC, tobias-93 commented on Resources/views/Form/form_html.html.twig
> +    {% set widgetIcon = 'fa-regular fa-calendar-days' %}
It is not necessary anymore

2023-11-21 20:00 UTC, tobias-93 commented on Resources/views/Form/form_html.html.twig
> +    {% set widgetIcon = 'fa-regular fa-clock' %}
It is not necessary anymore

2023-11-21 20:01 UTC, tobias-93 commented on Resources/public/bootstrap-collection/css/bootstrap-collection.css
No, since Font Awesome 6 will remove the `i` tag and replace it by an `svg` without the `fa` class, even if it has that class. So it will not work to filter on that anymore.

2023-11-21 20:01 UTC, tobias-93 commented on Resources/public/bootstrap-collection/css/bootstrap-collection.min.css
See previous comment

2023-11-21 20:01 UTC, merged